<section id="login" class="login-hero">
  <div class="container">
  <div class="login-box"> 
        <div class="row">
        <div class="col-md-6 login-left">
              <h2> Login </h2>
              <form action="validation.php" method="post">
                <div class="form-group">
                  <label>username</label> 
                  <input type="text" name="user" class="form-control" require>
                  </div>
                  <div class="form-group">
                  <laber>password</laber> 
                  <input type="password" name="password" class="form-control" require>
   </div> 
                  <button type="submit" class="btn-about"> Login </button>

</div>      
        <div class="col-md-6 login-right" >
              <h2> Sign Up </h2>
              <form action="registration.php" method="post">
                <div class="form-group">
                  <label>username</label> 
                  <input type="text" name="user" class="form-control" require>
                  </div>
                  <div class="form-group">
                  <label>password</label> 
                  <input type="password" name="password" class="form-control" require>
                  </div> 
                  <button type="submit" class="btn-about"> Sign Up </button>
                  </div>
  </section>

  <!--  <div class="container">
  <div class="login-box"> 
        <div class="row">    
        <div class="col-md-6 login-right" >
              <h2> Sign Up </h2>
              <form action="registration.php" method="post">
                <div class="form-group">
                  <label>username</label> 
                  <input type="text" name="user" class="form-control" require>
                  </div>
                  <div class="form-group">
                  <label>password</label> 
                  <input type="password" name="password" class="form-control" require>
                  </div> 
                  <button type="submit" class="btn-about"> Sign Up </button>
                  </div>
  </section> -->